name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Download yt-dlp (Windows)
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -OutFile yt-dlp.exe

      - name: Download yt-dlp (macOS)
        if: runner.os == 'macOS'
        run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
          chmod +x yt-dlp

      - name: Build and release Electron app
        uses: mauron85/action-electron-builder@1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS DMG Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: spotify-downloader-macos
          path: dist/*.dmg

      - name: Upload Windows Executable Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: spotify-downloader-windows
          path: dist/*.exe
