name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Download yt-dlp (Windows)
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -OutFile yt-dlp.exe

      - name: Download yt-dlp (macOS)
        if: runner.os == 'macOS'
        run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
          chmod +x yt-dlp

      - name: Build Electron app
        run: npx electron-builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS DMG Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: spotify-downloader-macos
          path: dist/*.dmg

      - name: Upload Windows Executable Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: spotify-downloader-windows
          path: dist/*.exe
